
convcommit_init_file() {
  local convcommit_file="$1"

  [ -f "${convcommit_file}" ] && return 0

  # shellcheck disable=SC2129
  echo "# convcommit - Conventional Commit message builder" >> "${convcommit_file}"
  echo "# This file is read by the \`convcommit\` CLI tool to populate" >> "${convcommit_file}"
  echo "# the interactive selector menus." >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# FORMAT" >> "${convcommit_file}"
  echo "#   type:<value>      — commit type option (e.g. fix, feat, docs)" >> "${convcommit_file}"
  echo "#   scope:<value>     — commit scope option" >> "${convcommit_file}"
  echo "#   message:<value>   — commit message template" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# SPECIAL PREFIXES" >> "${convcommit_file}"
  echo "#   ~<value>          — marks the default selection" >> "${convcommit_file}"
  echo "#   _                 — enables free-text manual input (press \".\")" >> "${convcommit_file}"
  echo "#   [X]<value>        — forces key letter X for this entry (e.g. [I]init, [W]wip)" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# HOW TO USE (interactive)" >> "${convcommit_file}"
  echo "#   Run \`convcommit\` in a git repo. A menu appears for type, scope, message." >> "${convcommit_file}"
  echo "#   Press the letter shown in brackets [A][B]... or [.] for manual input." >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# HOW TO USE (AI agent / non-interactive pipe)" >> "${convcommit_file}"
  echo "#   Pipe selections as lines, one per stage (type, scope, message)." >> "${convcommit_file}"
  echo "#   Use the letter shown in the menu, or \".\" to trigger manual input." >> "${convcommit_file}"
  echo "#   Example:" >> "${convcommit_file}"
  echo "#     printf \"A\n.\nfix null pointer in login\n\" | convcommit" >> "${convcommit_file}"
  echo "#   Or use direct flags to bypass the selector entirely:" >> "${convcommit_file}"
  echo "#     convcommit --type fix --scope auth --message \"fix null pointer\"" >> "${convcommit_file}"
  echo "#   To regenerate this file with the latest defaults:" >> "${convcommit_file}"
  echo "#     convcommit --reset" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# INSTALLATION" >> "${convcommit_file}"
  echo "#   convcommit is a single bash file with no dependencies." >> "${convcommit_file}"
  echo "#   Install it locally in your project:" >> "${convcommit_file}"
  echo "#     curl -fsSL https://raw.githubusercontent.com/francescobianco/convcommit/refs/heads/main/bin/convcommit \\" >> "${convcommit_file}"
  echo "#       -o bin/convcommit && chmod +x bin/convcommit" >> "${convcommit_file}"
  echo "#   Or system-wide:" >> "${convcommit_file}"
  echo "#     curl -fsSL https://raw.githubusercontent.com/francescobianco/convcommit/refs/heads/main/bin/convcommit \\" >> "${convcommit_file}"
  echo "#       -o /usr/local/bin/convcommit && chmod +x /usr/local/bin/convcommit" >> "${convcommit_file}"
  echo "type:[B]build" >> "${convcommit_file}"
  echo "type:~chore" >> "${convcommit_file}"
  echo "type:[D]docs" >> "${convcommit_file}"
  echo "type:deps" >> "${convcommit_file}"
  echo "type:feat" >> "${convcommit_file}"
  echo "type:fix" >> "${convcommit_file}"
  echo "type:ci" >> "${convcommit_file}"
  echo "type:init" >> "${convcommit_file}"
  echo "type:merge" >> "${convcommit_file}"
  echo "type:perf" >> "${convcommit_file}"
  echo "type:refactor" >> "${convcommit_file}"
  echo "type:revert" >> "${convcommit_file}"
  echo "type:security" >> "${convcommit_file}"
  echo "type:style" >> "${convcommit_file}"
  echo "type:test" >> "${convcommit_file}"
  echo "type:[W]wip" >> "${convcommit_file}"
  echo "scope:_" >> "${convcommit_file}"
  echo "scope:~" >> "${convcommit_file}"
  echo "message:_" >> "${convcommit_file}"
  echo "message:~_" >> "${convcommit_file}"
}
