
convcommit_init_file() {
  local convcommit_file="$1"

  [ -f "${convcommit_file}" ] && return 0

  # shellcheck disable=SC2129
  echo "# convcommit - Conventional Commit message builder" >> "${convcommit_file}"
  echo "# This file is read by the \`convcommit\` CLI tool to populate" >> "${convcommit_file}"
  echo "# the interactive selector menus." >> "${convcommit_file}"
  echo "# Commit this file to share the project's commit vocabulary with the team." >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# FORMAT" >> "${convcommit_file}"
  echo "#   type:<value>      — commit type option (e.g. fix, feat, docs)" >> "${convcommit_file}"
  echo "#   scope:<value>     — commit scope option" >> "${convcommit_file}"
  echo "#   message:<value>   — commit message template" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# SPECIAL PREFIXES" >> "${convcommit_file}"
  echo "#   ~<value>          — marks the default selection" >> "${convcommit_file}"
  echo "#   _                 — enables free-text manual input (press \".\")" >> "${convcommit_file}"
  echo "#   [X]<value>        — forces key letter X for this entry (e.g. [B]build, [W]wip)" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# HOW TO USE (interactive)" >> "${convcommit_file}"
  echo "#   Run \`convcommit\` in a git repo. A menu appears for type, scope, message." >> "${convcommit_file}"
  echo "#   Press the letter in brackets [A][B]... or [.] for free-text input." >> "${convcommit_file}"
  echo "#   Stage and push in one shot:" >> "${convcommit_file}"
  echo "#     convcommit -a -p" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# HOW TO USE (direct flags — scripts, AI agents)" >> "${convcommit_file}"
  echo "#   Bypass the selector entirely with explicit flags:" >> "${convcommit_file}"
  echo "#     convcommit --type fix --scope auth --message \"fix null pointer\" --push" >> "${convcommit_file}"
  echo "#     convcommit -t feat -s api -m \"add endpoint\" -a -p" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# SMART PATTERN — stage specific files and commit in one command" >> "${convcommit_file}"
  echo "#   Use --add instead of nested command substitution." >> "${convcommit_file}"
  echo "#   Anti-pattern (avoid):" >> "${convcommit_file}"
  echo "#     msg=\$(convcommit --type fix --message \"fix\") && git commit -m \"\$msg\" && git push" >> "${convcommit_file}"
  echo "#   Recommended:" >> "${convcommit_file}"
  echo "#     convcommit --add src/auth.sh --type fix --scope auth --message \"fix null pointer\" --push" >> "${convcommit_file}"
  echo "#   Stage multiple files:" >> "${convcommit_file}"
  echo "#     convcommit --add src/auth.sh --add tests/auth_test.sh -t test -s auth -m \"add tests\" -p" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# HOW TO USE (pipe / non-interactive)" >> "${convcommit_file}"
  echo "#   Pipe selections as lines: one per stage (type, scope, message)." >> "${convcommit_file}"
  echo "#   Use the letter shown in the menu, or \".\" to trigger free-text input." >> "${convcommit_file}"
  echo "#   Examples:" >> "${convcommit_file}"
  echo "#     printf \"G\n.\nfix null pointer in login\n\" | convcommit" >> "${convcommit_file}"
  echo "#     printf \"F\n\nadd endpoint\n\" | convcommit -a -p" >> "${convcommit_file}"
  echo "#   Capture just the formatted message:" >> "${convcommit_file}"
  echo "#     msg=\$(printf \"G\n\nfix null pointer\n\" | convcommit)" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# OTHER USEFUL FLAGS" >> "${convcommit_file}"
  echo "#   --reset   Regenerate this file with the latest defaults" >> "${convcommit_file}"
  echo "#   --help    Show all options" >> "${convcommit_file}"
  echo "#" >> "${convcommit_file}"
  echo "# INSTALLATION" >> "${convcommit_file}"
  echo "#   convcommit is a single bash file with no dependencies." >> "${convcommit_file}"
  echo "#   Install it locally in your project:" >> "${convcommit_file}"
  echo "#     curl -fsSL https://raw.githubusercontent.com/francescobianco/convcommit/refs/heads/main/bin/convcommit \\" >> "${convcommit_file}"
  echo "#       -o bin/convcommit && chmod +x bin/convcommit" >> "${convcommit_file}"
  echo "#   Or system-wide:" >> "${convcommit_file}"
  echo "#     curl -fsSL https://raw.githubusercontent.com/francescobianco/convcommit/refs/heads/main/bin/convcommit \\" >> "${convcommit_file}"
  echo "#       -o /usr/local/bin/convcommit && chmod +x /usr/local/bin/convcommit" >> "${convcommit_file}"
  echo "type:[B]build" >> "${convcommit_file}"
  echo "type:~chore" >> "${convcommit_file}"
  echo "type:[D]docs" >> "${convcommit_file}"
  echo "type:deps" >> "${convcommit_file}"
  echo "type:feat" >> "${convcommit_file}"
  echo "type:fix" >> "${convcommit_file}"
  echo "type:ci" >> "${convcommit_file}"
  echo "type:init" >> "${convcommit_file}"
  echo "type:merge" >> "${convcommit_file}"
  echo "type:perf" >> "${convcommit_file}"
  echo "type:refactor" >> "${convcommit_file}"
  echo "type:revert" >> "${convcommit_file}"
  echo "type:security" >> "${convcommit_file}"
  echo "type:style" >> "${convcommit_file}"
  echo "type:test" >> "${convcommit_file}"
  echo "type:[W]wip" >> "${convcommit_file}"
  echo "scope:_" >> "${convcommit_file}"
  echo "scope:~" >> "${convcommit_file}"
  echo "message:_" >> "${convcommit_file}"
  echo "message:~_" >> "${convcommit_file}"
}
